name: Build and Push Jini Supervisor (Machine 2)

on:
  push:
    branches:
      - main
    paths:
      - 'supervisor.py'
      - 'Dockerfile_supervisor'
      - 'jini_router_core.py'

jobs:
  build-and-push-supervisor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Control Plane Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Yeh GitHub khud generate karta hai, aapko add nahi karna padega

      - name: Build and Push Supervisor Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_supervisor
          push: true
          tags: ghcr.io/akashdeployerjiten/jini_supervisor:latest
          